# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFoxHuntGame', '0005_powerup_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerup',
            name='PU_time',
            field=models.TimeField(default=0),
        ),
    ]
