# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IFoxHuntGame', '0006_auto_20151209_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerup',
            name='PU_time',
        ),
    ]
