# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFoxHuntGame', '0007_remove_powerup_pu_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerup',
            name='message',
            field=models.TextField(default='Congrats you got a powerup!'),
        ),
    ]
